# Generated by Django 4.1.2 on 2022-10-11 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignActivity",
            fields=[
                ("itemCode", models.CharField(max_length=15, null=True, unique=True)),
                ("itemDescrp", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Acitivity",
                "ordering": ("itemCode",),
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                ("Code", models.CharField(max_length=2, null=True)),
                ("Description", models.CharField(max_length=50, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplines",
                "ordering": ("Description",),
            },
        ),
        migrations.CreateModel(
            name="DocSubItem",
            fields=[
                ("Code", models.CharField(max_length=6, null=True, unique=True)),
                ("Description", models.CharField(max_length=50, null=True)),
                ("WBS", models.CharField(max_length=3, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Sub-Items",
                "ordering": ("Description",),
            },
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                ("Code", models.CharField(max_length=5, null=True, unique=True)),
                ("Status", models.CharField(max_length=60, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Status",
                "ordering": ("Status",),
            },
        ),
        migrations.CreateModel(
            name="ItemCode",
            fields=[
                (
                    "itemCode",
                    models.CharField(
                        max_length=15, null=True, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "itemDescrp",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Codes",
                "ordering": ("itemCode",),
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                ("itemCode", models.CharField(max_length=15, null=True, unique=True)),
                ("itemDescrp", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStructure",
            fields=[
                ("Code", models.CharField(max_length=15, null=True, unique=True)),
                ("Description", models.CharField(max_length=50, null=True)),
                ("WBS", models.CharField(max_length=6, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Structures",
                "ordering": ("Code",),
            },
        ),
        migrations.CreateModel(
            name="ProjectSubStructure",
            fields=[
                ("Code", models.CharField(max_length=15, null=True, unique=True)),
                ("Description", models.CharField(max_length=50, null=True)),
                ("WBS", models.CharField(max_length=6, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Sub-Structures",
                "ordering": ("Code",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseCategory",
            fields=[
                ("Code", models.CharField(max_length=5, null=True, unique=True)),
                ("Category", models.CharField(max_length=60, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Categories",
                "ordering": ("Code",),
            },
        ),
        migrations.CreateModel(
            name="ScopeOfWork",
            fields=[
                (
                    "quoteNumber",
                    models.CharField(blank=True, max_length=15, unique=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyCategory",
            fields=[
                (
                    "itemCode",
                    models.CharField(
                        max_length=15, null=True, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "ordering": ("itemCode",),
            },
        ),
        migrations.CreateModel(
            name="SupportActivity",
            fields=[
                (
                    "itemCode",
                    models.CharField(
                        max_length=15, null=True, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "itemDescrp",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Activity",
                "ordering": ("itemCode",),
            },
        ),
        migrations.CreateModel(
            name="SupportQuotation",
            fields=[
                (
                    "activityDescr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Activity Description",
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("EASY", "EASY"),
                            ("AVERAGE", "AVERAGE"),
                            ("COMPLEX", "COMPLEX"),
                        ],
                        default="COMPLEX",
                        max_length=20,
                        null=True,
                        verbose_name="Complexity",
                    ),
                ),
                ("estHours", models.IntegerField(verbose_name=" Est. Hrs")),
                ("actualHours", models.IntegerField(verbose_name="Actual. Hrs")),
                (
                    "unitCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "markupMargin",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Mark-Up"
                    ),
                ),
                (
                    "subTotalValue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.designactivity",
                        verbose_name="Activity Class",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.discipline",
                        verbose_name="Disc.",
                    ),
                ),
                (
                    "itemCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.itemcode",
                        verbose_name="Item Code",
                    ),
                ),
                (
                    "quoteNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoteNumber5",
                        to="quotations.scopeofwork",
                        verbose_name="Quote Number",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.resource",
                        verbose_name="Resource",
                    ),
                ),
            ],
            options={
                "ordering": ["itemCode"],
            },
        ),
        migrations.CreateModel(
            name="SupplyQuotation",
            fields=[
                (
                    "activityDescr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Supply Description",
                    ),
                ),
                (
                    "supplierRef",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Reference"
                    ),
                ),
                (
                    "handFee",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Handl.Fee"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Qty")),
                (
                    "unitsOfMeasure",
                    models.CharField(
                        choices=[("EACH", "EACH"), ("METER", "METER"), ("KG", "KG")],
                        default="EACH",
                        max_length=20,
                        null=True,
                        verbose_name="Units",
                    ),
                ),
                (
                    "unitCost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("markupMargin", models.DecimalField(decimal_places=1, max_digits=4)),
                ("supplierDisc", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "subTotalValue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "itemCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.itemcode",
                        verbose_name="Item Code",
                    ),
                ),
                (
                    "materialCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.supplycategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "quoteNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoteNumber4",
                        to="quotations.scopeofwork",
                        verbose_name="Quote Number",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.company",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["itemCode"],
            },
        ),
        migrations.CreateModel(
            name="ScopeOfWorkInclusions",
            fields=[
                (
                    "itemCode",
                    models.CharField(
                        choices=[
                            ("Item 1", "Item 1"),
                            ("Item 2", "Item 2"),
                            ("Item 3", "Item 3"),
                            ("Item 4", "Item 4"),
                            ("Item 5", "Item 5"),
                            ("Item 6", "Item 6"),
                            ("Item 7", "Item 7"),
                            ("Item 8", "Item 8"),
                            ("Item 9", "Item 9"),
                            ("Item 10", "Item 10"),
                            ("Item 11", "Item 11"),
                            ("Item 12", "Item 12"),
                            ("Item 14", "Item 14"),
                            ("Item 15", "Item 15"),
                            ("Item 16", "Item 16"),
                            ("Item 17", "Item 17"),
                            ("Item 18", "Item 18"),
                            ("Item 19", "Item 19"),
                            ("Item 20", "Item 20"),
                            ("Item 21", "Item 21"),
                            ("Item 22", "Item 22"),
                            ("Item 23", "Item 23"),
                        ],
                        max_length=10,
                        verbose_name="Item Codes",
                    ),
                ),
                (
                    "inclusion",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Scope of Work"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, null=True, verbose_name="Qty"),
                ),
                (
                    "units",
                    models.CharField(max_length=10, null=True, verbose_name="Units"),
                ),
                (
                    "delivery_time",
                    models.IntegerField(default=1, null=True, verbose_name="Delivery"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quoteNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quoteNumber1",
                        to="quotations.scopeofwork",
                    ),
                ),
            ],
            options={
                "ordering": ["itemCode"],
            },
        ),
        migrations.CreateModel(
            name="ScopeOfWorkExclusion",
            fields=[
                (
                    "itemCode",
                    models.CharField(
                        choices=[
                            ("Item 1", "Item 1"),
                            ("Item 2", "Item 2"),
                            ("Item 3", "Item 3"),
                            ("Item 4", "Item 4"),
                            ("Item 5", "Item 5"),
                            ("Item 6", "Item 6"),
                            ("Item 7", "Item 7"),
                            ("Item 8", "Item 8"),
                            ("Item 9", "Item 9"),
                            ("Item 10", "Item 10"),
                            ("Item 11", "Item 11"),
                            ("Item 12", "Item 12"),
                            ("Item 14", "Item 14"),
                            ("Item 15", "Item 15"),
                            ("Item 16", "Item 16"),
                            ("Item 17", "Item 17"),
                            ("Item 18", "Item 18"),
                            ("Item 19", "Item 19"),
                            ("Item 20", "Item 20"),
                            ("Item 21", "Item 21"),
                            ("Item 22", "Item 22"),
                            ("Item 23", "Item 23"),
                        ],
                        max_length=10,
                        verbose_name="Item Codes",
                    ),
                ),
                (
                    "exclusion",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Exclusions"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quoteNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoteNumber2",
                        to="quotations.scopeofwork",
                        verbose_name="Quote Number",
                    ),
                ),
            ],
            options={
                "ordering": ["itemCode"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "quoteNumber",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Quote Number",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Quote Title",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[("ABA", "ABACUS"), ("HCE", "HCE")],
                        default="HCE",
                        max_length=20,
                        null=True,
                        verbose_name="Division",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Quote Date"
                    ),
                ),
                (
                    "quote_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Postponed", "Postponed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Delivery (weeks)",
                    ),
                ),
                (
                    "delivery_details",
                    models.CharField(
                        blank=True,
                        default="Delivery time will be confirmed on receipt of official purchase order",
                        max_length=150,
                        null=True,
                        verbose_name="Notes on Delivery",
                    ),
                ),
                (
                    "quote_validity",
                    models.CharField(
                        blank=True,
                        default="60 days validity",
                        max_length=300,
                        null=True,
                        verbose_name="Validity",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        default="30 days after date of invoice",
                        max_length=300,
                        null=True,
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "clientName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "compiler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teammember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("Code", models.CharField(max_length=3, null=True, unique=True)),
                ("Description", models.CharField(max_length=60, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "WBS",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quotations.docsubitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Types",
                "ordering": ("Code",),
            },
        ),
        migrations.AddField(
            model_name="discipline",
            name="WBS",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotations.projectstructure",
            ),
        ),
        migrations.CreateModel(
            name="DesignQuotation",
            fields=[
                (
                    "activityDescr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Activity Description",
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("EASY", "EASY"),
                            ("AVERAGE", "AVERAGE"),
                            ("COMPLEX", "COMPLEX"),
                        ],
                        default="COMPLEX",
                        max_length=20,
                        null=True,
                        verbose_name="Complexity",
                    ),
                ),
                ("estHours", models.IntegerField(verbose_name=" Est. Hrs")),
                (
                    "actualHours",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Actual. Hrs"
                    ),
                ),
                (
                    "unitCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "markupMargin",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Mark-Up"
                    ),
                ),
                (
                    "subTotalValue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.designactivity",
                        verbose_name="Activity Class",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.discipline",
                        verbose_name="Disc.",
                    ),
                ),
                (
                    "itemCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotations.itemcode",
                        verbose_name="Item Code",
                    ),
                ),
                (
                    "quoteNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoteNumber3",
                        to="quotations.scopeofwork",
                        verbose_name="Quote Number",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.resource",
                        verbose_name="Resource",
                    ),
                ),
            ],
            options={
                "ordering": ["itemCode"],
            },
        ),
    ]
