# Generated by Django 4.1.2 on 2022-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportquotation",
            options={},
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="activityDescr",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="actualHours",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="discipline",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="estHours",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="itemCode",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="markupMargin",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="quoteNumber",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="subTotalValue",
        ),
        migrations.RemoveField(
            model_name="supportquotation",
            name="unitCost",
        ),
        migrations.AlterField(
            model_name="supportquotation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
