# Generated by Django 4.1.2 on 2022-10-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="companyLogo",
        ),
        migrations.AlterField(
            model_name="company",
            name="companyEmail",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Company Email"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyWeb",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Company Website"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="customer",
            field=models.CharField(
                default=True, max_length=50, verbose_name="Customer"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_created",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Date Created"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_latest_order",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Latest Order"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_latest_quote",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Latest Quotation"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplier",
            field=models.CharField(
                default=False, max_length=50, verbose_name="Supplier"
            ),
        ),
    ]
