# Generated by Django 4.1.2 on 2022-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_company_companylogo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contID",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="Contact ID"
            ),
        ),
    ]
