# Generated by Django 4.1.2 on 2022-10-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_contact_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_of_birth",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Date of Birth"
            ),
        ),
    ]
