# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\HCEC Dropbox\HCE-Server\_EEMS\forms\massbalance.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MassBalance(object):
    def setupUi(self, MassBalance):
        MassBalance.setObjectName("MassBalance")
        MassBalance.resize(1498, 855)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MassBalance.sizePolicy().hasHeightForWidth())
        MassBalance.setSizePolicy(sizePolicy)
        self.label_22 = QtWidgets.QLabel(MassBalance)
        self.label_22.setGeometry(QtCore.QRect(450, 10, 571, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.lbProject = QtWidgets.QLabel(MassBalance)
        self.lbProject.setGeometry(QtCore.QRect(460, 50, 571, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbProject.sizePolicy().hasHeightForWidth())
        self.lbProject.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbProject.setFont(font)
        self.lbProject.setText("")
        self.lbProject.setAlignment(QtCore.Qt.AlignCenter)
        self.lbProject.setObjectName("lbProject")
        self.tableView = QtWidgets.QTableView(MassBalance)
        self.tableView.setGeometry(QtCore.QRect(20, 100, 1461, 511))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(MassBalance)
        QtCore.QMetaObject.connectSlotsByName(MassBalance)

    def retranslateUi(self, MassBalance):
        _translate = QtCore.QCoreApplication.translate
        MassBalance.setWindowTitle(_translate("MassBalance", "Dialog"))
        self.label_22.setText(_translate("MassBalance", "MASS BALANCE"))
