# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\_EEMS\forms\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupForm(object):
    def setupUi(self, SignupForm):
        SignupForm.setObjectName("SignupForm")
        SignupForm.resize(420, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\_EEMS\\forms\\../resources/icons/HCE-C.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignupForm.setWindowIcon(icon)
        self.logoFrame = QtWidgets.QFrame(SignupForm)
        self.logoFrame.setGeometry(QtCore.QRect(10, 10, 401, 131))
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.lbLogo = QtWidgets.QLabel(self.logoFrame)
        self.lbLogo.setGeometry(QtCore.QRect(110, 0, 181, 121))
        self.lbLogo.setText("")
        self.lbLogo.setPixmap(QtGui.QPixmap("Z:/__CUSTOMER LOGOS/HCE.png"))
        self.lbLogo.setObjectName("lbLogo")
        self.lbLogo_2 = QtWidgets.QLabel(self.logoFrame)
        self.lbLogo_2.setGeometry(QtCore.QRect(50, 20, 301, 91))
        self.lbLogo_2.setText("")
        self.lbLogo_2.setPixmap(QtGui.QPixmap("C:\\_EEMS\\forms\\../resources/assets/HCE-logo.jpg"))
        self.lbLogo_2.setScaledContents(True)
        self.lbLogo_2.setObjectName("lbLogo_2")
        self.registerFrame = QtWidgets.QFrame(SignupForm)
        self.registerFrame.setGeometry(QtCore.QRect(10, 150, 401, 431))
        self.registerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.registerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.registerFrame.setObjectName("registerFrame")
        self.label = QtWidgets.QLabel(self.registerFrame)
        self.label.setGeometry(QtCore.QRect(16, 20, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.registerBlock = QtWidgets.QFrame(self.registerFrame)
        self.registerBlock.setGeometry(QtCore.QRect(10, 70, 371, 331))
        self.registerBlock.setStyleSheet("QFrame {\n"
" border: 1px solid gray;\n"
" border-radius: 10px;\n"
"}")
        self.registerBlock.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.registerBlock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.registerBlock.setObjectName("registerBlock")
        self.leEmail = QtWidgets.QLineEdit(self.registerBlock)
        self.leEmail.setGeometry(QtCore.QRect(10, 90, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leEmail.setFont(font)
        self.leEmail.setStyleSheet("QLineEdit {\n"
" border: 1px solid gray;\n"
" border-radius: 10px;\n"
"}")
        self.leEmail.setObjectName("leEmail")
        self.lePassword = QtWidgets.QLineEdit(self.registerBlock)
        self.lePassword.setGeometry(QtCore.QRect(10, 150, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lePassword.setFont(font)
        self.lePassword.setStyleSheet("QLineEdit {\n"
" border: 1px solid gray;\n"
" border-radius: 10px;\n"
"}")
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.lbEmail = QtWidgets.QLabel(self.registerBlock)
        self.lbEmail.setGeometry(QtCore.QRect(20, 70, 341, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.lbEmail.setFont(font)
        self.lbEmail.setStyleSheet("border: 0px")
        self.lbEmail.setLineWidth(0)
        self.lbEmail.setObjectName("lbEmail")
        self.lbPassword = QtWidgets.QLabel(self.registerBlock)
        self.lbPassword.setGeometry(QtCore.QRect(20, 130, 341, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.lbPassword.setFont(font)
        self.lbPassword.setStyleSheet("border: 0px")
        self.lbPassword.setLineWidth(0)
        self.lbPassword.setObjectName("lbPassword")
        self.btnRegister = QtWidgets.QPushButton(self.registerBlock)
        self.btnRegister.setGeometry(QtCore.QRect(130, 290, 101, 31))
        self.btnRegister.setStyleSheet("   QPushButton {\n"
"         border: 1px solid gray;\n"
"         border-radius: 10px;\n"
"         background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                           stop: 0 #f6f7fa, stop: 1 rgb(0, 0, 223) );\n"
"\n"
"     }\n"
"\n"
" QPushButton:pressed {\n"
"         background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                           stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"     }")
        self.btnRegister.setObjectName("btnRegister")
        self.lbConfirmpass = QtWidgets.QLabel(self.registerBlock)
        self.lbConfirmpass.setGeometry(QtCore.QRect(20, 190, 341, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.lbConfirmpass.setFont(font)
        self.lbConfirmpass.setStyleSheet("border: 0px")
        self.lbConfirmpass.setLineWidth(0)
        self.lbConfirmpass.setObjectName("lbConfirmpass")
        self.leConfirmpass = QtWidgets.QLineEdit(self.registerBlock)
        self.leConfirmpass.setGeometry(QtCore.QRect(10, 210, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leConfirmpass.setFont(font)
        self.leConfirmpass.setStyleSheet("QLineEdit {\n"
" border: 1px solid gray;\n"
" border-radius: 10px;\n"
"}")
        self.leConfirmpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leConfirmpass.setObjectName("leConfirmpass")
        self.lbInvalid = QtWidgets.QLabel(self.registerBlock)
        self.lbInvalid.setGeometry(QtCore.QRect(20, 260, 321, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.lbInvalid.setFont(font)
        self.lbInvalid.setStyleSheet("border: 0px")
        self.lbInvalid.setLineWidth(0)
        self.lbInvalid.setAlignment(QtCore.Qt.AlignCenter)
        self.lbInvalid.setObjectName("lbInvalid")
        self.leUserName = QtWidgets.QLineEdit(self.registerBlock)
        self.leUserName.setGeometry(QtCore.QRect(10, 30, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leUserName.setFont(font)
        self.leUserName.setMouseTracking(True)
        self.leUserName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leUserName.setStyleSheet("QLineEdit {\n"
" border: 1px solid gray;\n"
" border-radius: 10px;\n"
"}")
        self.leUserName.setObjectName("leUserName")
        self.lbLastName = QtWidgets.QLabel(self.registerBlock)
        self.lbLastName.setGeometry(QtCore.QRect(20, 10, 341, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.lbLastName.setFont(font)
        self.lbLastName.setStyleSheet("border: 0px")
        self.lbLastName.setLineWidth(0)
        self.lbLastName.setObjectName("lbLastName")
        self.label_2 = QtWidgets.QLabel(self.registerFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 410, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(SignupForm)
        QtCore.QMetaObject.connectSlotsByName(SignupForm)

    def retranslateUi(self, SignupForm):
        _translate = QtCore.QCoreApplication.translate
        SignupForm.setWindowTitle(_translate("SignupForm", "Form"))
        self.label.setText(_translate("SignupForm", "Register to continue to HCE EEMS System"))
        self.lbEmail.setText(_translate("SignupForm", "Email Address"))
        self.lbPassword.setText(_translate("SignupForm", "Password"))
        self.btnRegister.setText(_translate("SignupForm", "Register"))
        self.lbConfirmpass.setText(_translate("SignupForm", "Confirm Password"))
        self.lbInvalid.setText(_translate("SignupForm", "Invalid Email or Password"))
        self.lbLastName.setText(_translate("SignupForm", "Username"))
        self.label_2.setText(_translate("SignupForm", " 2022 Developed by HCE"))
from . import resources_rc
