# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\HCEC Dropbox\HCE-Server\_EEMS\forms\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeForm(object):
    def setupUi(self, WelcomeForm):
        WelcomeForm.setObjectName("WelcomeForm")
        WelcomeForm.resize(997, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\HCEC Dropbox\\HCE-Server\\_EEMS\\forms\\../resources/icons/HCE-C.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WelcomeForm.setWindowIcon(icon)
        self.logoFrame = QtWidgets.QFrame(WelcomeForm)
        self.logoFrame.setGeometry(QtCore.QRect(10, 10, 981, 571))
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.label = QtWidgets.QLabel(self.logoFrame)
        self.label.setGeometry(QtCore.QRect(350, 60, 271, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\HCEC Dropbox\\HCE-Server\\_EEMS\\forms\\../resources/assets/HCE-C.png"))
        self.label.setObjectName("label")
        self.btnLogin = QtWidgets.QPushButton(self.logoFrame)
        self.btnLogin.setGeometry(QtCore.QRect(230, 440, 521, 31))
        self.btnLogin.setStyleSheet("   QPushButton {\n"
"         border: 1px solid gray;\n"
"         border-radius: 10px;\n"
"         background-color:  rgb(0, 170, 255);\n"
"     }\n"
"\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(self.logoFrame)
        self.btnRegister.setGeometry(QtCore.QRect(230, 520, 521, 31))
        self.btnRegister.setStyleSheet("   QPushButton {\n"
"         border: 1px solid gray;\n"
"         border-radius: 10px;\n"
"         background-color:  rgb(0, 170, 255);\n"
"\n"
"     }\n"
"")
        self.btnRegister.setObjectName("btnRegister")

        self.retranslateUi(WelcomeForm)
        QtCore.QMetaObject.connectSlotsByName(WelcomeForm)

    def retranslateUi(self, WelcomeForm):
        _translate = QtCore.QCoreApplication.translate
        WelcomeForm.setWindowTitle(_translate("WelcomeForm", "Form"))
        self.btnLogin.setText(_translate("WelcomeForm", "Log in"))
        self.btnRegister.setText(_translate("WelcomeForm", "Create New Account"))
from . import resources_rc
