# Generated by Django 4.1.2 on 2022-10-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MassBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Stream Number"
                    ),
                ),
                (
                    "stream_descrip",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Stream Description",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Area"
                    ),
                ),
                (
                    "solid_mass_flow",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Solid Mass Flow t/h",
                    ),
                ),
                (
                    "water_mass_flow",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Water Mass Flow t/h",
                    ),
                ),
                (
                    "slurry_mass_flow",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Slurry Mass Flow m3/h",
                    ),
                ),
                (
                    "percentage_moisture",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Percentate moisture wt %",
                    ),
                ),
                (
                    "percentage_solids",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Percentate solids wt %",
                    ),
                ),
                (
                    "solids_density",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Solids Density t/m3",
                    ),
                ),
                (
                    "water_density",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Water Density t/m3",
                    ),
                ),
                (
                    "solids_bulk_density",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Solids Bulk Density t/m3",
                    ),
                ),
                (
                    "slurry_density",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Slurry Density t/m3",
                    ),
                ),
                (
                    "solid_particle_size_P100",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="P100 (mm)"
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Notes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteConditions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
