# Generated by Django 4.1.2 on 2022-10-11 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SAISCSteelSections",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=25,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Profile Type"
                    ),
                ),
                (
                    "unit_mass",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Unit Mass (kg/m)",
                    ),
                ),
                (
                    "h",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Height (mm)"
                    ),
                ),
                (
                    "b",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Width (mm)"
                    ),
                ),
                (
                    "c",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Lip Height (mm)",
                    ),
                ),
                (
                    "d",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Diameter (mm)",
                    ),
                ),
                (
                    "tw",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Wed / Wall Thickness (mm)",
                    ),
                ),
                (
                    "tf",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Thickness (mm)",
                    ),
                ),
                (
                    "r1",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Web Radius (mm)",
                    ),
                ),
                (
                    "r2",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Radius (mm)",
                    ),
                ),
                (
                    "b1",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Taper Centre (mm)",
                    ),
                ),
                (
                    "Beta",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Taper Flange Angle (deg)",
                    ),
                ),
                (
                    "A",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Cross sectional Area (mm2)",
                    ),
                ),
                (
                    "Ix",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Second Moment of Area about x-x (mm4)",
                    ),
                ),
                (
                    "Zx",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sectional Modulus about x-x (mm3)",
                    ),
                ),
                (
                    "rx",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Radius of Gyration about x-x (mm)",
                    ),
                ),
                (
                    "Iy",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Second Moment of Area about y-y (mm4)",
                    ),
                ),
                (
                    "Zy",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sectional Modulus about y-y (mm3)",
                    ),
                ),
                (
                    "ry",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Radius of Gyration about y-y (mm)",
                    ),
                ),
                (
                    "Iu",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Second Moment of Area about u-u (mm4)",
                    ),
                ),
                (
                    "Zu",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sectional Modulus about u-u (mm3)",
                    ),
                ),
                (
                    "ru",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Radius of Gyration about u-u (mm)",
                    ),
                ),
                (
                    "Iv",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Second Moment of Area about v-v (mm4)",
                    ),
                ),
                (
                    "Zv",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sectional Modulus about v-v (mm3)",
                    ),
                ),
                (
                    "rv",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Radius of Gyration about v-v (mm)",
                    ),
                ),
                (
                    "J",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Polar Moment (mm4)",
                    ),
                ),
                (
                    "Cw",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Warping Constant (mm6)",
                    ),
                ),
                (
                    "Zplx",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Plastic Sectional Modulus about x-x (mm3)",
                    ),
                ),
                (
                    "Zply",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Plastic Sectional Modulus about y-y (mm3)",
                    ),
                ),
                (
                    "h_tf",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Height to Flange Thickness Ratio",
                    ),
                ),
                (
                    "hw",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Internal Height (mm)",
                    ),
                ),
                (
                    "ac",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Shear Centre (mm)",
                    ),
                ),
                (
                    "ax",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Shear Centre (mm)",
                    ),
                ),
                (
                    "ay",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Shear Centre (mm)",
                    ),
                ),
                (
                    "alpha",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="(deg)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SANSPlateFlanges",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "nom_bore",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nominal Bore Diameter",
                    ),
                ),
                (
                    "flange_mass",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Mass (kg)",
                    ),
                ),
                (
                    "pressureRating",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Pressure Rating (kPa)",
                    ),
                ),
                (
                    "flange_type",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Type Configuration",
                    ),
                ),
                (
                    "pipeOutsideDia",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Pipe Outside Diameter (mm)",
                    ),
                ),
                (
                    "flangeOutsideDia",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Outside Diameter (mm)",
                    ),
                ),
                (
                    "flangeThickness",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Flange Thickness (mm)",
                    ),
                ),
                (
                    "raisedFaceDia",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Raised Face Diameter (mm)",
                    ),
                ),
                (
                    "raisedFaceThick",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Raised Face Thickness (mm)",
                    ),
                ),
                (
                    "boltSize",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Bolt Size"
                    ),
                ),
                (
                    "NOB",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Number of Bolts",
                    ),
                ),
                (
                    "boltHoleSize",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Bolt Hole Diameter (mm)",
                    ),
                ),
                (
                    "PCD",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Bolt Holes Centres (mm)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
