# Generated by Django 4.1.2 on 2022-10-12 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkMaterialData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "material",
                    models.CharField(max_length=40, null=True, verbose_name="Material"),
                ),
                (
                    "condition",
                    models.CharField(
                        max_length=40, null=True, verbose_name="Condition"
                    ),
                ),
                (
                    "minBD",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Minimum Bulk Density (kg/m^3)",
                    ),
                ),
                (
                    "maxBD",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Maximum Bulk Density (kg/m^3)",
                    ),
                ),
                (
                    "SG",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Specific Weight"
                    ),
                ),
                (
                    "maxBeltIncline",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Maximum Belt Incline (deg)",
                    ),
                ),
                (
                    "maxBeltLoadingAngle",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Maximum Belt Loading (deg)",
                    ),
                ),
                (
                    "angleOfRepose",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Angle of Repose (deg)"
                    ),
                ),
                (
                    "minInternalFrictionAngle",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Minimum Internal Friction Angle (deg)",
                    ),
                ),
                (
                    "maxInternalFrictionAngle",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="MAximum Internal Friction Angle (deg)",
                    ),
                ),
                (
                    "minWallFrictionAngle",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Minimum Wall Friction Angle (deg)",
                    ),
                ),
                (
                    "maxWallFrictionAngle",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Minimum Wall Friction Angle (deg)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarryIdler",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Series"
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
                (
                    "idlerDiameter",
                    models.CharField(
                        blank=True,
                        choices=[("127", "127"), ("152", "152")],
                        max_length=40,
                        null=True,
                        verbose_name="Idler Designation",
                    ),
                ),
                (
                    "idlerFaceLength",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Face Length (mm)",
                    ),
                ),
                (
                    "idlerFrameLength",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Idler Frame (mm)",
                    ),
                ),
                (
                    "idlerFrameMountCtrs",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Idler Mount Centres (mm)",
                    ),
                ),
                (
                    "topOfBottomRoller",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Distance to Top of Bottom Roller (mm)",
                    ),
                ),
                (
                    "numOfMountHoles",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Number of Mount Hole",
                    ),
                ),
                (
                    "mountHoleSize",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Mount Holes Dimensions",
                    ),
                ),
                (
                    "rotatingMass",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Rotating Mass (kg)",
                    ),
                ),
                (
                    "totalMass",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Total Mass (kg)",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Carry Idler Height (mm)",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Distance between Trough Idlers (mm)",
                    ),
                ),
                (
                    "bearingSpec",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Bearing Specification",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConveyorBeltClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConveyorPulley",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "pulleyType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Head/Drive Pulley", "Head/Drive Pulley"),
                            ("Head Pulley", "Head Pulley"),
                            ("Snub Pulley", "Snub Pulley"),
                            ("Bend Pulley", "Bend Pulley"),
                            ("Drive Pulley", "Drive Pulley"),
                            ("Tail Pulley", "Tail Pulley"),
                            ("Tail/Take-Up Pulley", "Tail/Take-Up Pulley"),
                            ("Take-Up Pulley", "Take-Up Pulley"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Pulley Type",
                    ),
                ),
                (
                    "pulleyLoadType",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
                (
                    "outsideDia",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Pulley Outside Diameter (mm)",
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("450", "450"),
                            ("500", "500"),
                            ("600", "600"),
                            ("750", "750"),
                            ("900", "900"),
                            ("1050", "1050"),
                            ("1200", "1200"),
                            ("1350", "1350"),
                            ("1500", "1500"),
                            ("1650", "1650"),
                            ("1800", "1800"),
                            ("2100", "2100"),
                            ("2400", "2400"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
                (
                    "faceLength",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Face Length (mm)",
                    ),
                ),
                (
                    "wallThickness",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Wall Thickness (mm)",
                    ),
                ),
                (
                    "hubeType",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Hub Type"
                    ),
                ),
                (
                    "shaftDiameter",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Shaft Diameter (mm)",
                    ),
                ),
                (
                    "bearingDiameter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50", "50"),
                            ("65", "65"),
                            ("75", "75"),
                            ("90", "90"),
                            ("100", "100"),
                            ("115", "115"),
                            ("125", "125"),
                            ("140", "140"),
                            ("150", "150"),
                            ("160", "160"),
                            ("180", "180"),
                            ("190", "190"),
                            ("200", "200"),
                            ("220", "220"),
                            ("240", "240"),
                            ("260", "260"),
                            ("280", "280"),
                            ("300", "300"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Bearing Diameter (mm)",
                    ),
                ),
                (
                    "soleplate",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Sole Plate)"
                    ),
                ),
                (
                    "hubThickness",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Hub Thickness (mm)",
                    ),
                ),
                (
                    "bearingCentre",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Bearing Centres (mm)",
                    ),
                ),
                (
                    "plummberBlock",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Plummer Block",
                    ),
                ),
                (
                    "lagging",
                    models.CharField(
                        blank=True,
                        choices=[("Plain", "Plain"), ("Diamond", "Diamond")],
                        max_length=40,
                        null=True,
                        verbose_name="Lagging Type",
                    ),
                ),
                (
                    "laggingThick",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Lagging Thickness (mm)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnIdler",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Series"
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolePLatePlummerBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "bearingshaftDia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50", "50"),
                            ("65", "65"),
                            ("75", "75"),
                            ("90", "90"),
                            ("100", "100"),
                            ("115", "115"),
                            ("125", "125"),
                            ("140", "140"),
                            ("150", "150"),
                            ("160", "160"),
                            ("180", "180"),
                            ("190", "190"),
                            ("200", "200"),
                            ("220", "220"),
                            ("240", "240"),
                            ("260", "260"),
                            ("280", "280"),
                            ("300", "300"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Bearing SHaft Diameter (mm)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConveyorReturnIdler",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("450", "450"),
                            ("500", "500"),
                            ("600", "600"),
                            ("750", "750"),
                            ("900", "900"),
                            ("1050", "1050"),
                            ("1200", "1200"),
                            ("1350", "1350"),
                            ("1500", "1500"),
                            ("1650", "1650"),
                            ("1800", "1800"),
                            ("2100", "2100"),
                            ("2400", "2400"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Series"
                    ),
                ),
                (
                    "vAngle",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="V Angle (deg)",
                    ),
                ),
                (
                    "numOfRollers",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Number of Rollers",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "idlerDesignation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="techdata.returnidler",
                        verbose_name="Idler Designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConveyorCarryIdler",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("450", "450"),
                            ("500", "500"),
                            ("600", "600"),
                            ("750", "750"),
                            ("900", "900"),
                            ("1050", "1050"),
                            ("1200", "1200"),
                            ("1350", "1350"),
                            ("1500", "1500"),
                            ("1650", "1650"),
                            ("1800", "1800"),
                            ("2100", "2100"),
                            ("2400", "2400"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Width (mm)",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Series"
                    ),
                ),
                (
                    "troughAngle",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Trough Angle (deg)",
                    ),
                ),
                (
                    "numOfRollers",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Number of Rollers",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "idlerDesignation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="techdata.carryidler",
                        verbose_name="Idler Designation",
                    ),
                ),
            ],
        ),
    ]
