# Generated by Django 4.1.2 on 2022-10-12 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "techdata",
            "0003_alter_bulkmaterialdata_id_alter_conveyorbeltclass_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnidler",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
