# Generated by Django 4.1.2 on 2022-10-12 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0004_alter_returnidler_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConveyorBelt",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Project Number",
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("450", "450"),
                            ("500", "500"),
                            ("600", "600"),
                            ("750", "750"),
                            ("900", "900"),
                            ("1050", "1050"),
                            ("1200", "1200"),
                            ("1350", "1350"),
                            ("1500", "1500"),
                            ("1650", "1650"),
                            ("1800", "1800"),
                            ("2100", "2100"),
                            ("2400", "2400"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Width",
                    ),
                ),
                (
                    "beltType",
                    models.CharField(
                        blank=True,
                        choices=[("Fabric", "Fabric"), ("Steel Core", "Steel Core")],
                        max_length=40,
                        null=True,
                        verbose_name="Belt Construction",
                    ),
                ),
                (
                    "beltTopCover",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Top Cover (mm)",
                    ),
                ),
                (
                    "beltBottomCover",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Bottom Cover (mm)",
                    ),
                ),
                (
                    "feedRate",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Feed Rate (t/h)",
                    ),
                ),
                (
                    "beltSpeed",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Belt Speed (m/s)",
                    ),
                ),
                (
                    "horizontalDist",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Horizontal Distance (mm)",
                    ),
                ),
                (
                    "verticalList",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Vertical Lift (mm)",
                    ),
                ),
                (
                    "maxInclinedAngle",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Maximum Inclined Angle (deg)",
                    ),
                ),
                (
                    "maxLoadingAngle",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Maximum Belt Loading Angle (deg)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "beltClass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="techdata.conveyorbeltclass",
                        verbose_name="Belt Class",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="techdata.bulkmaterialdata",
                        verbose_name="Feed Material",
                    ),
                ),
            ],
        ),
    ]
