# Generated by Django 4.1.2 on 2022-10-18 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0005_conveyorbelt"),
    ]

    operations = [
        migrations.CreateModel(
            name="IECElectricalMotors",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "motorPower",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Motor Power"
                    ),
                ),
                (
                    "motorSpeed",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Motor Speed"
                    ),
                ),
                (
                    "poles",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Number of Poles",
                    ),
                ),
                (
                    "frame",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Frame Size"
                    ),
                ),
                (
                    "shaft",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Shaft Size"
                    ),
                ),
                (
                    "keywaywidth",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Key Way Width",
                    ),
                ),
                (
                    "keywayheight",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Key Way Depth",
                    ),
                ),
                (
                    "shaftkeydepth",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Key Way Depth",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Frame Size"
                    ),
                ),
                (
                    "shaft_height",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Vertical Distance to Shaft",
                    ),
                ),
                (
                    "full_load_torque",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Full Load Torque",
                    ),
                ),
                (
                    "lock_rotor_torque",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Lock Rotor Torque",
                    ),
                ),
                (
                    "break_torque",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Lock Rotor Torque",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
