# Generated by Django 4.1.2 on 2022-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0006_iecelectricalmotors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iecelectricalmotors",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
