# Generated by Django 4.1.2 on 2022-10-18 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0007_alter_iecelectricalmotors_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardKeyways",
            fields=[
                (
                    "designation",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Designation"
                    ),
                ),
                (
                    "from_dia",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="From"
                    ),
                ),
                (
                    "to_dia",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="To"
                    ),
                ),
                (
                    "keywidth",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Key Width"
                    ),
                ),
                (
                    "keyheight",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Key Height"
                    ),
                ),
                (
                    "maxkeylength",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Maximum Key Length",
                    ),
                ),
                (
                    "shaftkeydepth",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Shaft Key Depth",
                    ),
                ),
                (
                    "hubkeydepth",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Hub Key Depth",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="iecelectricalmotors",
            name="designation",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="Designation"
            ),
        ),
        migrations.AlterField(
            model_name="iecelectricalmotors",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
