# Generated by Django 4.1.2 on 2022-10-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0008_standardkeyways_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iecelectricalmotors",
            name="mounting",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Mounting"
            ),
        ),
    ]
