# Generated by Django 4.1.2 on 2022-10-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0009_iecelectricalmotors_mounting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soleplateplummerblock",
            old_name="bearingshaftDia",
            new_name="bearShaftDia",
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimA",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension A"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimC",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension C"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimD",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension D"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimE",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension E"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimF",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension F"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimF1",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension F1"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimG",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension G"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimH",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension H"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimJ",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension J"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimK",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension K"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimL",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension L"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimM",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension M"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimN",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension N"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimS",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension S"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimT",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension T"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="dimU",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Dimension U"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="plumBlock",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Plummer Block"
            ),
        ),
    ]
