# Generated by Django 4.1.2 on 2022-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "techdata",
            "0010_rename_bearingshaftdia_soleplateplummerblock_bearshaftdia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="adapterSleeve",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Adapter Sleeve"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="bearing",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Bearing"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="lockRing",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Lock Ring"
            ),
        ),
        migrations.AddField(
            model_name="soleplateplummerblock",
            name="seal",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="seal"
            ),
        ),
    ]
