# Generated by Django 4.1.2 on 2022-10-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0011_soleplateplummerblock_adaptersleeve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carryidler",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="soleplateplummerblock",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
