# Generated by Django 4.1.2 on 2022-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techdata", "0012_alter_carryidler_id_alter_soleplateplummerblock_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConveyorPulleyDimension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beltWidth",
                    models.CharField(
                        max_length=40, null=True, unique=True, verbose_name="Belt Width"
                    ),
                ),
                (
                    "face_length",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Face Length"
                    ),
                ),
                (
                    "dimA",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension A"
                    ),
                ),
                (
                    "dimB",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension C"
                    ),
                ),
                (
                    "dimC",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension D"
                    ),
                ),
                (
                    "dimD",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension E"
                    ),
                ),
                (
                    "dimE",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension F"
                    ),
                ),
                (
                    "dimG",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Dimension F1"
                    ),
                ),
                (
                    "maxShaftDia",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Maximum Shaft Diamter",
                    ),
                ),
            ],
        ),
    ]
